version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ../csv-data/mysql:/var/lib/mysql
      - ../csv-data/data:/data
    networks:
      - default
  app:
    build: .
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
    command: bash -c 'ruby main.rb'
    volumes:
      - .:/workspace
      - ../csv-data/data:/data
      - ../csv-data/targets:/list
    networks:
      - default
